version: '1.0'

services:
  server:
    build: server/
    command: python ./server.py
    ports:
      - "4455:4455"
    volumes:
      - servervol:/server/serverdata
  



  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
    volumes:
      - clientvol:/client/clientdata
volumes:
  servervol:
  clientvol:
